//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYTradingPublicSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Glove
    {
        public Glove()
        {
            this.GloveApplications = new HashSet<GloveApplication>();
            this.ImagePaths = new HashSet<ImagePath>();
        }
    
        public int GloveID { get; set; }
        public string ItemNo { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Sizes { get; set; }
        public string Colors { get; set; }
        public int MaterialID { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual ICollection<GloveApplication> GloveApplications { get; set; }
        public virtual ICollection<ImagePath> ImagePaths { get; set; }
    }
}
