//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYTradingPublicSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GloveApplication
    {
        public int GloveApplicationID { get; set; }
        public int GloveID { get; set; }
        public int ApplicationID { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Glove Glove { get; set; }
    }
}
